### ISSUE TITLE
Missing Dependency in README [+ Fedora 21 Install Instructions]

### ISSUE THREAD

**Issue by keckelt** [MasterSoft24/Grive2#6]
Hi,
i just managed to install Grive2 on Fedora 21, but besides:

``` shell
sudo yum install cmake libgcrypt-devel json-c-devel libcurl-devel boost-devel
```

I **also** had to install:

``` shell
sudo yum instal yajl-devel
```

And change your hardcoded home directory [_/home/ms/NetBeansProjects/_ and so on] to a different one with _sed_.

**Comment by donvipre** [comment]
on fresh Fedora 22 i solved it with:

sudo dnf -y install yajl-devel boost-devel libcurl-devel libstdc++-devel libgcrypt-devel cmake gcc-c++ expat-devel

**Comment by MasterSoft24** [comment]
Note for  install devel packages  was added
