### ISSUE TITLE
Why are there 2 grive2 projects?

### ISSUE THREAD

**Issue by bernd-wechner** [MasterSoft24/Grive2#9]
I'm confused. I installed grive2 and it be broken, so I wanted to fetch the source and diagnose my issues and consider a fix. But looked at GitHib and found this and:

https://github.com/vitalif/grive2

The difference being only the case on the G, Grive2 vs. grive2. What gives? Why two projects? What's the difference? Can it get any more confusing?

**Comment by vitalif** [comment]
@MasterSoft24 +1, can you indicate that your version in a fork of mine or rename it to "grive3" or so? :)

**Comment by vitalif** [comment]
А, всё, понял, ты свой форк сделал ещё раньше, до появления моего =)

Но всё равно, напиши пожалуйста в описание, что это твой личный форк? А то до оригинального автора хрен достучишься, в итоге всем непонятно, где актуальная версия, потому что организация Grive заброшена...

**Comment by MasterSoft24** [comment]
Да, я форкнул оригинальный grive добавил в него белые и черные списки. А потом, после того, как гугл сменил api, я уже перенес свои правки в твой код. В описании ,вроде написано, что это форк оригинального grive, а версия 0.3 основана на твоих правках.

**Comment by vitalif** [comment]
Ну там слабо понятно... народ же не особо вдумываясь читает =)) можешь написать в README в начало несколько строчек типа вот так как-нибудь?

This is my (@MasterSoft24, Vladimir Kamensky) fork, based on https://github.com/vitalif/grive2/, with support for the following additional features:
- --list option
- .include/.exclude files

И в описание репозитория где "Grive2 is a Google Drive (online storage service) client for GNU/Linux" что-нибудь типа "Fork of Grive2 with support for --list and .include/.exclude"

Теоретически ещё можно пересоздать репозиторий на гитхабе через "fork", предварительно переименовав этот, и потом форсированно скопировать туда всё отсюда, тогда типа гитхаб бы писал "fork of ...", но это уже так, извращения...

**Comment by MasterSoft24** [comment]
Да, наверное, так правильнее будет. перепишу ридми и заголовок))

**Comment by vitalif** [comment]
Ага спасибо =)
Я ещё там как раз сегодня страничку завёл с инструкциями https://yourcmc.ru/wiki/Grive2 - может заодно прибьёшь http://mastersoft24.github.io/Grive2/ чтобы опять-таки было понятно, что где?
По идее больше всего мне хочется до оригинального автора, @nestal'а этого несчастного, достучаться, может он даст контроль над http://github.com/Grive, чтобы там порядок навести... но пока не удавалось, не отвечает :-(
Кстати, если есть желание присоединиться к разработке, или пакетики какие-нибудь куда-нибудь опубликовать типа PPA или ещё куда - welcome =)

**Comment by MasterSoft24** [comment]
Хорошо. Я для арча pkgbuild поддерживаю. Но думаю надо бы заняться и  deb c rpm. Для полного, так сказать, комплекта.

**Comment by vitalif** [comment]
Это, прибей http://mastersoft24.github.io/Grive2/ и в описание напиши что это форк плз...

**Comment by MasterSoft24** [comment]
Что то  я не пойму, как прибить http://mastersoft24.github.io/Grive2/. Вроде бранч удалил, но страница осталась.... А про форк я вроде написал.

**Comment by vitalif** [comment]
А всё, уже прибилась.
Ты напиши я имею ввиду в описание самого репозитория, где щас "Grive2 is a Google Drive (online storage service) client for GNU/Linux"
